function Get-ConfigTXT {
    param (
        $PathtoConfigTXT,
        [Switch]$NoBuptest
    )
    
    # $PathtoConfigTXT = "C:\Users\Matt\OneDrive\Documents\DiskPartitioner\Assets\AmigaFiles\EMU68Boot\config11.txt"
    # $PathtoConfigTXT = "C:\Users\Matt\OneDrive\Documents\DiskPartitioner\Assets\AmigaFiles\EMU68Boot\configlegacy.txt"

    $ConfigTxt = Get-Content -Path $PathtoConfigTXT
    
    $RevisedConfigTxt = @(
    
@"
# Config.txt for PiStorm
# Generated by Emu68 Imager v$($Script:Settings.Version)
# SD Card prepared on: $((Get-Date).ToString("yyyy-MM-dd HH:mm:ss"))
# This file is generated based on the settings you have selected in Emu68 Imager. If you wish to change any of these settings after the SD Card has been prepared, you can edit this file with a text editor either on your Amiga or on your PC/Mac.
 
"@
)

    If ($Script:GUIActions.ScreenModetoUse -eq "Custom"){
        $CVTAspectRatio = (Get-CVTAspectRatio -AspectRatio $Script:GUIActions.CustomScreenMode_Aspect)
        $CVTMargins = (get-cvtMargins -Margins $Script:GUIActions.CustomScreenMode_Margins)
        $CVTInterlace = (get-cvtInterlace -Interlace $Script:GUIActions.CustomScreenMode_Interlace)
        $CVTRB = (get-cvtBlanking -RB $Script:GUIActions.CustomScreenMode_RB)
        $CVT_String = "$($Script:GUIActions.CustomScreenMode_Width) $($Script:GUIActions.CustomScreenMode_Height) $($Script:GUIActions.CustomScreenMode_Framerate) $CVTAspectRatio $CVTMargins $CVTInterlace $CVTRB" 
    }

    $RevisedConfigTxt += foreach ($Line in $ConfigTxt) {
        switch ($Line) {
            "[DTOVERLAY_DIAGNOSTIC]" {
                if (-not $NoBuptest) {
                    "dtoverlay=diagnostic"
                    ""
                    "dtparam=buptest"
                    "dtparam=bupsize=512"
                    "dtparam=bupiter=1"
                }
                break
            }
            "[DTOVERLAY_EMU68]" { 
                # Intentionally left blank based on original code
                break 
            }
            "[DTOVERLAY_NOSCSI]" {
                if ($Script:GUIActions.SCSIDeviceDisabled -eq $true) { "dtoverlay=noscsi" }
                break
            }
            "[DTOVERLAY_PAL]" {
                if ($Script:GUIActions.AgnusType -eq "PAL") { "dtoverlay=PAL" }
                break
            }
            "[DTOVERLAY_NTSC]" {
                if ($Script:GUIActions.AgnusType -eq "NTSC") { "dtoverlay=NTSC" }
                break
            }
            "[DTOVERLAY_SDHC]" {
                "dtoverlay=sdhc"
                ""
                "dtparam=unit0=rw"
                if ($Script:GUIActions.DMAEnabled -eq $true) { "dtparam=DMA" }
                if ($Script:GUIActions.IRQEnabled -eq $true) { "dtparam=IRQ" }  
                if ($Script:GUIActions.SDLowSpeed -eq $true) { "dtparam=low_speed" } 
                if ([string]::IsNullOrWhiteSpace($Script:GUIActions.SDOverClockSpeed) -eq $false) { "dtparam=Speed=$($Script:GUIActions.SDOverClockSpeed)" }
                break
            }
            "[DTOVERLAY_EMMC]" {
                "dtoverlay=emmc"
                ""
                "dtparam=unit0=rw"
                if ($Script:GUIActions.DMAEnabled -eq $true) { "dtparam=DMA" }
                if ($Script:GUIActions.IRQEnabled -eq $true) { "dtparam=IRQ" }  
                if ($Script:GUIActions.SDLowSpeed -eq $true) { "dtparam=low_speed" } 
                if ([string]::IsNullOrWhiteSpace($Script:GUIActions.SDOverClockSpeed) -eq $false) { "dtparam=Speed=$($Script:GUIActions.SDOverClockSpeed)" }
                break
            }
            "[DTOVERLAY_UNICAM]" {
                if ($Script:GUIActions.UnicamEnabled -eq $true) {
                    "dtoverlay=unicam"
                    ""
                    if ($Script:GUIActions.UnicamStartonBoot -eq $true) { "dtparam=boot" }       
                    # Workaround for FT parameter not working                                
                    if (([string]::IsNullOrWhiteSpace($Script:GUIActions.UnicamDeviceType) -eq $false) -and ($Script:GUIActions.UnicamDeviceType -ne "ft")) { "dtparam=type=$($Script:GUIActions.UnicamDeviceType)" }
                    if ($Script:GUIActions.UnicamScalingType -eq "Smooth") {
                        "dtparam=smooth"
                        "dtparam=b=$($Script:GUIActions.UnicamBParameter)"
                        "dtparam=c=$($Script:GUIActions.UnicamCParameter)"
                    }

                    elseif ($Script:GUIActions.UnicamScalingType -eq "Integer") {
                        "dtparam=$($DTParamPrefix)integer"
                    }
                    if (([string]::IsNullOrWhiteSpace($Script:GUIActions.UnicamScanLinesNonLaced) -eq $false) -or ([string]::IsNullOrWhiteSpace($Script:GUIActions.UnicamScanLinesLaced) -eq $false)) {
                        "dtparam=$($DTParamPrefix)sc=$($Script:GUIActions.UnicamScanLinesNonLaced)"
                        "dtparam=$($DTParamPrefix)scl=$($Script:GUIActions.UnicamScanLinesLaced)"
                    }
                }
                break
            }
            "[ROMPATH]" {
                "initramfs /$($Script:GUIActions.FoundKickstarttoUse.Where({$_.KickstartVersion}).Fat32Name)"
                break
            }
            "[VIDEOMODES]" {
                "# The following section defines the screenmode for your monitor for output from the Raspberry Pi. If you wish to "
                "# select a different screenmode you can comment out the existing mode by adding a # to the beginning of the line "
                "# and removing the # the line of the new screenmode you wish to use."
                if ($Script:GUIActions.ScreenModetoUse -eq "Custom") {
                    "hdmi_cvt=$CVT_String"
                    "hdmi_group=2"
                    "hdmi_mode=87"
                }   
                foreach ($ScreenMode in $Script:GUIActions.AvailableScreenModes) {
                    ""                 
                    if ($ScreenMode.Name -eq $Script:GUIActions.ScreenModetoUse) {
                        $CommentedOutCharacter = ""
                        "# ScreenMode: $($ScreenMode.FriendlyName) (Currently Selected)"
                    } 
                    else {
                        $CommentedOutCharacter = "# "
                        "# ScreenMode: $($ScreenMode.FriendlyName)"
                    }
                    # Properties to map dynamically if they contain data
                    $Properties = @('hdmi_group', 'hdmi_mode', 'hdmi_cvt', 'max_framebuffer_width', 'max_framebuffer_height', 'hdmi_pixel_freq_limit', 'disable_overscan')
                    foreach ($Property in $Properties) {
                        if ($null -ne $ScreenMode.$Property -and $ScreenMode.$Property.ToString().Trim() -ne "") {
                            "${CommentedOutCharacter}${Property}=$($ScreenMode.$Property)"
                        }
                    }
                }       
                break
            }
            default {
                $Line
            }
        }
    }
    
    return $RevisedConfigTxt

}
