function Update-ConfigTXT {
    param (
        $PathtoConfigTXT,
        $PathtoExportedConfigTXT
    )
    
    # $PathtoConfigTXT = "C:\Users\Matt\OneDrive\Documents\EmuImager2\Assets\AmigaFiles\EMU68Boot\config.txt"
    # $PathtoExportedConfigTXT ="C:\Users\Matt\OneDrive\Documents\EmuImager2\Temp\InterimAmigaDrives\Emu68Boot\config.txt"

    $ConfigTxt = Get-Content -Path $PathtoConfigTXT
    Write-InformationMessage -Message 'Preparing Config.txt'
    $RevisedConfigTxt = @()
    
    If ($Script:GUIActions.ScreenModetoUse -eq "Custom"){
        $CVTAspectRatio = (Get-CVTAspectRatio -AspectRatio $Script:GUIActions.CustomScreenMode_Aspect)
        $CVTMargins = (get-cvtMargins -Margins $Script:GUIActions.CustomScreenMode_Margins)
        $CVTInterlace = (get-cvtInterlace -Interlace $Script:GUIActions.CustomScreenMode_Interlace)
        $CVTRB = (get-cvtBlanking -RB $Script:GUIActions.CustomScreenMode_RB)
        $CVT_String = "$($Script:GUIActions.CustomScreenMode_Width) $($Script:GUIActions.CustomScreenMode_Height) $($Script:GUIActions.CustomScreenMode_Framerate) $CVTAspectRatio $CVTMargins $CVTInterlace $CVTRB"
    }

    # Advanced mode knows the exact hardware, so it does not need the large
    # GPIO-based universal boot template.
    if ($Script:GUIActions.PiStormModel) {
        if ($Script:GUIActions.UnicamEnabled -eq $true) {
            if ($Script:GUIActions.PiStormModel -eq 'Classic PiStorm') {
                $Kernel = 'Emu68-pistorm-classic.gz'
            }
            else {
                $Kernel = 'Emu68-pistorm.gz'
            }
        }
        elseif ($Script:GUIActions.PiStormModel -eq 'PiStorm32Lite') {
            $Kernel = 'Emu68-pistorm32lite'
        }
        else {
            $Kernel = 'Emu68-pistorm'
        }

        $RevisedConfigTxt += '# config.txt generated by Emu68 Imager'
        $RevisedConfigTxt += "# Hardware: $($Script:GUIActions.PiStormModel)"
        $RevisedConfigTxt += ''
        $RevisedConfigTxt += '# Emu68 kernel and basic boot settings'
        $RevisedConfigTxt += "kernel=$Kernel"
        $RevisedConfigTxt += 'disable_splash=1'
        $RevisedConfigTxt += 'arm_64bit=1'
        $RevisedConfigTxt += 'boot_delay=0'

        if ($Script:GUIActions.UnicamEnabled -eq $true) {
            $RevisedConfigTxt += 'avoid_warnings=2'
            $RevisedConfigTxt += 'force_turbo=1'
            $RevisedConfigTxt += 'over_voltage=4'
            $RevisedConfigTxt += 'arm_freq=1800'
        }
        else {
            $RevisedConfigTxt += 'avoid_warnings=1'
            $RevisedConfigTxt += 'gpu_mem=32'
        }

        $RevisedConfigTxt += ''
        $RevisedConfigTxt += '# Raspberry Pi HDMI output'
        $RevisedConfigTxt += 'hdmi_force_hotplug=1'
        if ($Script:GUIActions.ScreenModetoUse -eq 'Custom') {
            $RevisedConfigTxt += "hdmi_cvt=$CVT_String"
            $RevisedConfigTxt += 'hdmi_group=2'
            $RevisedConfigTxt += 'hdmi_mode=87'
        }
        else {
            $SelectedScreenMode = $Script:GUIActions.AvailableScreenModes | Where-Object Name -eq $Script:GUIActions.ScreenModetoUse | Select-Object -First 1
            @('hdmi_group', 'hdmi_mode', 'hdmi_cvt', 'max_framebuffer_width', 'max_framebuffer_height', 'hdmi_pixel_freq_limit', 'disable_overscan') | ForEach-Object {
                $PropertyName = $_
                $PropertyValue = $SelectedScreenMode.$PropertyName
                if ($null -ne $PropertyValue -and "$PropertyValue" -ne '') {
                    $RevisedConfigTxt += "$PropertyName=$PropertyValue"
                }
            }
        }

        $RevisedConfigTxt += ''
        $RevisedConfigTxt += '# Alternative HDMI examples (uncomment one pair and replace the active mode above)'
        $RevisedConfigTxt += '# 1080p 50 Hz'
        $RevisedConfigTxt += '#hdmi_group=1'
        $RevisedConfigTxt += '#hdmi_mode=31'
        $RevisedConfigTxt += '# 720p 60 Hz'
        $RevisedConfigTxt += '#hdmi_group=2'
        $RevisedConfigTxt += '#hdmi_mode=85'

        if ($Script:GUIActions.UnicamEnabled -eq $true) {
            $UnicamParameters = @()
            if ($Script:GUIActions.UnicamStartonBoot -eq $true) { $UnicamParameters += 'boot' }
            if ($Script:GUIActions.UnicamScalingType -eq 'Smooth') {
                $UnicamParameters += 'smooth'
                if ($null -ne $Script:GUIActions.UnicamBParameter -and "$($Script:GUIActions.UnicamBParameter)" -ne '') { $UnicamParameters += "b=$($Script:GUIActions.UnicamBParameter)" }
                if ($null -ne $Script:GUIActions.UnicamCParameter -and "$($Script:GUIActions.UnicamCParameter)" -ne '') { $UnicamParameters += "c=$($Script:GUIActions.UnicamCParameter)" }
            }
            elseif ($Script:GUIActions.UnicamScalingType -eq 'Integer') {
                $UnicamParameters += 'integer'
            }
            $OverlaySuffix = if ($UnicamParameters.Count) { ",$($UnicamParameters -join ',')" } else { '' }
            $RevisedConfigTxt += ''
            $RevisedConfigTxt += '# FrameThrower / Unicam (Emu68 1.1)'
            $RevisedConfigTxt += "dtoverlay=unicam$OverlaySuffix"
            $RevisedConfigTxt += '# Alternative scaling examples:'
            $RevisedConfigTxt += '#dtoverlay=unicam,boot,smooth,b=200,c=400'
            $RevisedConfigTxt += '#dtoverlay=unicam,boot,integer'
        }

        $RevisedConfigTxt += ''
        $RevisedConfigTxt += '# Kickstart ROM'
        $RevisedConfigTxt += "initramfs $($Script:GUIActions.FoundKickstarttoUse.Fat32Name)"
        Export-TextFileforAmiga -DatatoExport $RevisedConfigTxt -ExportFile $PathtoExportedConfigTXT -AddLineFeeds 'TRUE'
        return
    }

    foreach ($Line in $ConfigTxt) {
        if ($line -eq '[ROMPATH]'){
            $RevisedConfigTxt += "initramfs $($Script:GUIActions.FoundKickstarttoUse.Fat32Name)"
        }
        elseif ($line -eq '[DEFAULT_KERNEL]') {
            # Each GPIO section below selects the matching kernel.
        }
        elseif ($line -eq '[AVOID_WARNINGS]') {
            if ($Script:GUIActions.UnicamEnabled -eq $true) {
                $RevisedConfigTxt += 'avoid_warnings=2'
            }
            else {
                $RevisedConfigTxt += 'avoid_warnings=1'
            }
        }
        elseif ($line -eq '[CPU_SETTINGS]') {
            if ($Script:GUIActions.UnicamEnabled -eq $true) {
                $RevisedConfigTxt += 'force_turbo=1'
                $RevisedConfigTxt += 'over_voltage=4'
                $RevisedConfigTxt += 'arm_freq=1800'
            }
            else {
                $RevisedConfigTxt += '#force_turbo=1'
                $RevisedConfigTxt += '#over_voltage=4'
                $RevisedConfigTxt += '#arm_freq=1800'
                $RevisedConfigTxt += '#core_freq=500'
                $RevisedConfigTxt += '#sdram_freq=600'
            }
        }
        elseif ($line -eq '[GPU_MEMORY]') {
            if ($Script:GUIActions.UnicamEnabled -ne $true) {
                $RevisedConfigTxt += 'gpu_mem=32'
            }
        }
        elseif ($line -eq '[VIDEOMODES]'){
            $RevisedConfigTxt +="# The following section defines the screenmode for your monitor for output from the Raspberry Pi. If you wish to "
            $RevisedConfigTxt +="# select a different screenmode you can comment out the existing mode and remove the comment marks from the new one."        
            If ($Script:GUIActions.ScreenModetoUse -eq "Custom"){
                $RevisedConfigTxt += "hdmi_cvt=$CVT_String"
                $RevisedConfigTxt += "hdmi_group=2"
                $RevisedConfigTxt += "hdmi_mode=87"
            }   
            $Script:GUIActions.AvailableScreenModes | ForEach-Object {
                if ($_.Name -eq $Script:GUIActions.ScreenModetoUse){
                    $RevisedConfigTxt += ""
                    $RevisedConfigTxt += "# ScreenMode: $($_.FriendlyName) (Currently Selected). To enable a different screenmode, comment out this one and enable a different one."
                    if (-not ($_.hdmi_group.Length -eq 0)){
                        $RevisedConfigTxt += "hdmi_group=$($_.hdmi_group)"
                    }
                    if (-not ($_.hdmi_mode.Length -eq 0)){
                        $RevisedConfigTxt += "hdmi_mode=$($_.hdmi_mode)"
                    }
                    if (-not ($_.hdmi_cvt.length -eq 0)){
                        $RevisedConfigTxt += "hdmi_cvt=$($_.hdmi_cvt)"
                    }
                    if (-not ($_.max_framebuffer_width.length -eq 0)){
                        $RevisedConfigTxt += "max_framebuffer_width=$($_.max_framebuffer_width)"
                    }
                    if (-not ($_.max_framebuffer_height.length -eq 0)){
                        $RevisedConfigTxt += "max_framebuffer_height=$($_.max_framebuffer_height)"
                    }
                    if (-not ($_.hdmi_pixel_freq_limit.length -eq 0)){
                        $RevisedConfigTxt += "hdmi_pixel_freq_limit=$($_.hdmi_pixel_freq_limit)"
                    }
                    if (-not ($_.disable_overscan.length -eq 0)){
                        $RevisedConfigTxt += "disable_overscan=$($_.disable_overscan)"
                    }
                }
                else {
                    $RevisedConfigTxt += ""
                    $RevisedConfigTxt += "# ScreenMode: $($_.FriendlyName)"
                    if (-not ($_.hdmi_group.Length -eq 0)){
                        $RevisedConfigTxt += "# hdmi_group=$($_.hdmi_group)"
                    }
                    if (-not ($_.hdmi_mode.Length -eq 0)){
                        $RevisedConfigTxt += "# hdmi_mode=$($_.hdmi_mode)"
                    }
                    if (-not ($_.hdmi_cvt.length -eq 0)){
                        $RevisedConfigTxt += "# hdmi_cvt=$($_.hdmi_cvt)"
                    }
                    if (-not ($_.max_framebuffer_width.length -eq 0)){
                        $RevisedConfigTxt += "# max_framebuffer_width=$($_.max_framebuffer_width)"
                    }
                    if (-not ($_.max_framebuffer_height.length -eq 0)){
                        $RevisedConfigTxt += "# max_framebuffer_height=$($_.max_framebuffer_height)"
                    }
                    if (-not ($_.hdmi_pixel_freq_limit.length -eq 0)){
                        $RevisedConfigTxt += "# hdmi_pixel_freq_limit=$($_.hdmi_pixel_freq_limit)"
                    }
                    if (-not ($_.disable_overscan.length -eq 0)){
                        $RevisedConfigTxt += "# disable_overscan=$($_.disable_overscan)"
                    }
                }
            }
        }
        elseif ($line -eq '[FRAMETHROWER]') {
            if ($Script:GUIActions.UnicamEnabled -eq $true) {
                $UnicamParameters = @()
                if ($Script:GUIActions.UnicamStartonBoot -eq $true) {
                    $UnicamParameters += 'boot'
                }
                if ($Script:GUIActions.UnicamScalingType -eq 'Smooth') {
                    $UnicamParameters += 'smooth'
                    if ($null -ne $Script:GUIActions.UnicamBParameter -and "$($Script:GUIActions.UnicamBParameter)" -ne '') {
                        $UnicamParameters += "b=$($Script:GUIActions.UnicamBParameter)"
                    }
                    if ($null -ne $Script:GUIActions.UnicamCParameter -and "$($Script:GUIActions.UnicamCParameter)" -ne '') {
                        $UnicamParameters += "c=$($Script:GUIActions.UnicamCParameter)"
                    }
                }
                elseif ($Script:GUIActions.UnicamScalingType -eq 'Integer') {
                    $UnicamParameters += 'integer'
                }
                $OverlaySuffix = if ($UnicamParameters.Count) { ",$($UnicamParameters -join ',')" } else { '' }
                $RevisedConfigTxt += '# FrameThrower / Unicam settings for Emu68 1.1'
                $RevisedConfigTxt += "dtoverlay=unicam$OverlaySuffix"
            }
        }
        elseif ($line -eq '[KERNEL_PISTORM32LITE]') {
            if ($Script:GUIActions.UnicamEnabled -eq $true) {
                $RevisedConfigTxt += 'kernel=Emu68-pistorm.gz'
            }
            else {
                $RevisedConfigTxt += 'kernel=Emu68-pistorm32lite'
            }
        }
        elseif ($line -eq '[KERNEL_PISTORM16]') {
            if ($Script:GUIActions.UnicamEnabled -eq $true) {
                $RevisedConfigTxt += 'kernel=Emu68-pistorm.gz'
            }
            else {
                $RevisedConfigTxt += 'kernel=Emu68-pistorm'
            }
        }
        elseif ($line -eq '[KERNEL_PISTORM]') {
            if ($Script:GUIActions.UnicamEnabled -eq $true) {
                $RevisedConfigTxt += 'kernel=Emu68-pistorm-classic.gz'
            }
            else {
                $RevisedConfigTxt += 'kernel=Emu68-pistorm'
            }
        }
        else{
            $RevisedConfigTxt += "$Line"
        }    
    }

    Export-TextFileforAmiga -DatatoExport $RevisedConfigTxt -ExportFile $PathtoExportedConfigTXT -AddLineFeeds 'TRUE' 
    
}
