function Update-CmdlineTXT {
    param (
        $PathtoCmdlineTXT,
        $PathtoExportedCmdlineTXT,
        [Switch]$NoBuptest
    )
    

    if (Test-Path $PathtoExportedCmdlineTXT){
        $null = Remove-Item  $PathtoExportedCmdlineTXT -Force -ErrorAction SilentlyContinue
    }

    $CmdlineTxt = Get-Content -Path $PathtoCmdlineTXT
    Write-InformationMessage -Message "Preparing Cmdline.txt"
    $RevisedCmdlineTxt = @()
    
    $RevisedCmdlineTxt += "# Cmdline.txt for PiStorm"
    $RevisedCmdlineTxt += "# Generated by Emu68 Imager v$([string]$Script:Settings.Version)"
    $RevisedCmdlineTxt += "# SD Card prepared on: $((Get-Date).ToString("yyyy-MM-dd HH:mm:ss"))"
    $RevisedCmdlineTxt += "# This file is generated based on the settings you have selected in Emu68 Imager. If you wish to change any of these settings after the SD Card has been prepared, you can edit this file with a text editor either on your Amiga or on your PC/Mac."
    $RevisedCmdlineTxt += "#"

    foreach ($Line in $CmdlineTxt) {
        if ($line -eq '[CMDLINE]'){
            $CmdLinetoAdd = "sd.unit0=rw emmc.unit0=rw"
            if  (-not ($NoBupTest)){
                if  (($Script:GUIActions.InstallOSFiles -eq $true) -and (($Script:GUIActions.KickstartVersiontoUse).Major -eq 3) -and (($Script:GUIActions.KickstartVersiontoUse).Minor -eq 2)){
                    $CmdLinetoAdd = "buptest=512 bupiter=1 $CmdLinetoAdd" 
                } 
            }
            if ($Script:GUIActions.SDLowSpeed){
                $CmdLinetoAdd = "$CmdLinetoAdd sd.low_speed emmc.low_speed"
            }
            if ($Script:GUIActions.UnicamEnabled -eq $true){
                If ($Script:GUIActions.UnicamStartonBoot -eq $true){
                    $CmdLinetoAdd = "$CmdLinetoAdd unicam.boot"
                }
                if ($Script:GUIActions.UnicamScalingType -eq "Smooth"){
                    $CmdLinetoAdd = "$CmdLinetoAdd unicam.smooth unicam.b=$($Script:GUIActions.UnicamBParameter) unicam.c=$($Script:GUIActions.UnicamCParameter)"
    
                }
                elseif ($Script:GUIActions.UnicamScalingType -eq "Integer"){
                    $CmdLinetoAdd = "$CmdLinetoAdd unicam.integer"
    
                }
                if (($Script:GUIActions.UnicamScanLinesNonLaced) -or ($Script:GUIActions.UnicamScanLinesLaced)){
                    $CmdLinetoAdd = "$CmdLinetoAdd scanline=$($Script:GUIActions.UnicamScanLinesNonLaced),$($Script:GUIActions.UnicamScanLinesLaced)"
                }
            }
            $RevisedCmdlineTxt += $CmdLinetoAdd
        }
        else {
            $RevisedCmdlineTxt += $Line
        }
    }
            
    Export-TextFile -PC -DatatoExport $RevisedCmdlineTxt -ExportFile $PathtoExportedCmdlineTXT -AddLineFeeds
    
}
