$WPF_EditUnicamSettingsWindow_ScanlinesInterlaced_slider.add_ValueChanged({
    $WPF_EditUnicamSettingsWindow_ScanlinesInterlaced_value.Text = $WPF_EditUnicamSettingsWindow_ScanlinesInterlaced_slider.Value
})