function Read-ConfigFile {
    param ()
    
$DefaultConfigFile=@"
# Emu68 Imager Config file
# Do not edit this file unless you know what you are doing! It will break Emu68 Imager! You have been warned!
# Change value below for HSTDetailedLog to True to enable detailed logging
# HSTDetailedLog=False
# Uncomment line below to disable parallel downloads and to not prompt on boot
# RunParallel=Never 
# Set Github API token to avoid unauthenticated limits (development and testing only)
# GithubAPIToken=
# Change value below for AllowVirtualDrives to True to enable use of a Virtual drive to act as SD card. Used for testing only!
# AllowVirtualDrives=True
"@    


    if (-not (Test-Path -Path $Script:Settings.ConfigFileLocation)) {
        $ConfigFile = $DefaultConfigFile -split '\r?\n'
        $ConfigFile | Set-Content -Path $Script:Settings.ConfigFileLocation
        return
    }

    $ConfigFile = Get-Content -Path $Script:Settings.ConfigFileLocation
    
    # Pass the collection directly into the switch; it will process line-by-line automatically
    switch -Regex ($ConfigFile) {
        # Skip comments or whitespace lines
        '^\s*#' { continue }
        '^\s*$' { continue }

        # Matches HSTDetailedLog=<value>
        '^HSTDetailedLog\s*=\s*(?<value>.*)$' {
            if ($Matches.value.Trim() -eq "True") {
                $Script:Settings.HSTDetailedLogEnabled = $true
                Write-InformationMessage -Message "HST Detailed Log Enabled"
            }
        }

        # Matches RunParallel=<value>
        '^RunParallel\s*=\s*(?<value>.*)$' {
            if ($Matches.value.Trim() -eq "Never") {
                $Script:GUIActionsCurrentStatus.RunParallelInstalled = "Never"
                Write-InformationMessage -Message "Run in Parallel Disabled"                
            }
        }
        '^GithubAPIToken\s*=\s*(?<value>.*)$' {
            $Script:GUICurrentStatus.GithubAPIToken = $Matches.value.Trim()
            Write-InformationMessage -Message "Github API Token set"                  
        }
        '^AllowVirtualDrives\s*=\s*(?<value>.*)$' {
            if ($Matches.value.Trim() -eq "True") {
                $Script:GUICurrentStatus.AllowVirtualDrives = $true
                Write-InformationMessage -Message "AllowVirtualDrives set"                  

            }
        }        
    }           
    return
}

