function Write-ConfigFile {
    param (
        [Switch]$RunParallel,
        [Switch]$HSTDetailedLog
    )

$DefaultConfigFile=@"
# Emu68 Imager Config file
# Do not edit this file unless you know what you are doing! It will break Emu68 Imager! You have been warned!
# Change value below for HSTDetailedLog to True to enable detailed logging
# HSTDetailedLog=False
# Uncomment line below to disable parallel downloads and to not prompt on boot
# RunParallel=Never 
# Set Github API token to avoid unauthenticated limits (development and testing only)
# GithubAPIToken=
# Change value below for AllowVirtualDrives to True to enable use of a Virtual drive to act as SD card. Used for testing only!
# AllowVirtualDrives=True
"@    

    $HSTDetailedLogText = if ($HSTDetailedLog.IsPresent) { "True" } else { "False" }


    if (Test-Path -Path $Script:Settings.ConfigFileLocation) {
        $ConfigFile = Get-Content -Path $Script:Settings.ConfigFileLocation
    }
    else {
        $ConfigFile = $DefaultConfigFile -split '\r?\n'
        
    }
    
    $TrackedSettings = @{}
    if ($RunParallel.IsPresent)     { $TrackedSettings['RunParallel']   = $false }
    if ($HSTDetailedLog.IsPresent) { $TrackedSettings['HSTDetailedLog'] = $false }
    # Future switches go here
    
    for ($i = 0; $i -lt $ConfigFile.Count; $i++) {
        switch -Regex ($ConfigFile[$i]) {
            '^RunParallel\s*=' {
                if ($TrackedSettings.ContainsKey('RunParallel')) {
                    $ConfigFile[$i] = "RunParallel=Never"
                    $TrackedSettings['RunParallel'] = $true
                }
            }
            '^HSTDetailedLog\s*=' {
                if ($TrackedSettings.ContainsKey('HSTDetailedLog')) {
                    $ConfigFile[$i] = "HSTDetailedLog=$HSTDetailedLogText"
                    $TrackedSettings['HSTDetailedLog'] = $true
                }
            }
        }
    }

    # 3. Append missing lines safely
    if ($TrackedSettings.ContainsKey('RunParallel') -and -not $TrackedSettings['RunParallel']) {
        $ConfigFile += "RunParallel=Never"
    }
    if ($TrackedSettings.ContainsKey('HSTDetailedLog') -and -not $TrackedSettings['HSTDetailedLog']) {
        $ConfigFile += "HSTDetailedLog=$HSTDetailedLogText"
    }

    # Save back to disk
    $ConfigFile | Set-Content -Path $Script:Settings.ConfigFileLocation

}